stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 0 # required for Nerdbank.Gitversioning support

content-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../Build"
  script:
    - cd Picturepark.ContentPortal.Demo/Picturepark.ContentPortal.Demo/ClientApp
    - node create-npmrc.js $gitpat
    - cd ../../../cake
    - powershell ./build.ps1 --target="PublishContentPortal"
  artifacts:
    paths:
      - Build/**

press-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../Build"
  script:
    - cd cake
    - powershell ./build.ps1 --target="PublishPressPortal"
  artifacts:
    paths:
      - Build/**
      - cake/**

.press-portal:deploy:
  stage: deploy
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  needs: [ "press-portal:build" ]
  variables:
    sourceDirectory: "../Build"
    serviceName: "Picturepark $PLATFORM DemoPressPortal"
    server: "$DEPLOY_TARGET"
    serverDirectory: "\\\\$DEPLOY_TARGET\\Integrations\\$PLATFORM\\Microsites\\DemoPressPortal\\"
  script:
    - net use \\$DEPLOY_TARGET /user:$SERVICE_MANAGER_USER $SERVICE_MANAGER_PASSWORD
    - cd cake
    - powershell ./build.ps1 --target="DeployPressPortal"
    
.content-portal:deploy:
  stage: deploy
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  needs: [ "content-portal:build" ]
  variables:
    sourceDirectory: "../Build"
    serviceName: "Picturepark $PLATFORM DemoContentPortal"
    server: "$DEPLOY_TARGET"
    serverDirectory: "\\\\$DEPLOY_TARGET\\Integrations\\$PLATFORM\\Microsites\\DemoContentPortal\\"
  script:
    - net use \\$DEPLOY_TARGET /user:$SERVICE_MANAGER_USER $SERVICE_MANAGER_PASSWORD
    - cd cake
    - powershell ./build.ps1 --target="DeployContentPortal"

press-portal:deploy:QA01:
  extends: .press-portal:deploy
  when: manual
  variables:
    PLATFORM: CPQA01
  environment:
    name: CPQA01 - Press Portal
    
press-portal:deploy:QA04:
  extends: .press-portal:deploy
  when: manual
  variables:
    PLATFORM: CPQA04
  environment:
    name: CPQA04 - Press Portal
  
content-portal:deploy:QA01:
  extends: .content-portal:deploy
  when: manual
  variables:
    PLATFORM: CPQA01
  environment:
    name: CPQA01 - Content Portal
  
content-portal:deploy:QA04:
  extends: .content-portal:deploy
  when: manual
  variables:
    PLATFORM: CPQA04
  environment:
    name: CPQA04 - Content Portal
