stages:
  - build

variables:
  GIT_DEPTH: 0 # required for Nerdbank.Gitversioning support

content-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../../Build"
  script:
    - cd Picturepark.ContentPortal.Demo/Picturepark.ContentPortal.Demo/ClientApp
    - node create-npmrc.js $gitpat
    - cd ../../../cake
    - powershell ./build.ps1 --target="PublishContentPortal"

press-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../../Build"
  script:
    - cd cake
    - powershell ./build.ps1 --target="PublishPressPortal"
