stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 0 # required for Nerdbank.Gitversioning support

content-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../Build"
  script:
    - cd Picturepark.ContentPortal.Demo/Picturepark.ContentPortal.Demo/ClientApp
    - node create-npmrc.js $gitpat
    - cd ../../../cake
    - powershell ./build.ps1 --target="PublishContentPortal"
  artifacts:
    paths:
      - Build/**

press-portal:build:
  stage: build
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  variables:
    sourceDirectory: "../Build"
  script:
    - cd cake
    - powershell ./build.ps1 --target="PublishPressPortal"
  artifacts:
    paths:
      - Build/**
      - cake/**

content-portal:deploy:
  stage: deploy
  image: gitlab-registry.vit.ch/picturepark/ci-containers/win-netcore-node-container
  tags:
    - build-docker-windows
  needs: [ "press-portal:build" ]
  when: manual
  variables:
    sourceDirectory: "../Build"
    serviceName: "Picturepark CPQA01 DemoPressPortal"
    server: "PP9QASVC01.ad.vit.ch"
    serverDirectory: "\\\\pp9qasvc01.ad.vit.ch\\Integrations\\CPQA01\\Microsites\\DemoPressPortal\\"
  script:
    - net use \\pp9qasvc01.ad.vit.ch /user:$SERVICE_MANAGER_USER $SERVICE_MANAGER_PASSWORD
    - cd cake
    - powershell ./build.ps1 --target="DeployPressPortal"
  
