apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/ingress.class: "{{ .Values.ingress.class }}"
  name: {{ include "sample-press-portal.fullname" . }}
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sample-press-portal.fullname" . }}
                port:
                  number: 5000
