apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-content-portal.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "sample-content-portal.name" . }}
  ports:
    - protocol: TCP
      port: 5000
